name: Argon UI Build

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set CHANNEL
        id: channel
        run: |
          msg="${{ github.event.head_commit.message }}"
          if echo "$msg" | grep -iq "#canary"; then echo "channel=canary" >> "$GITHUB_OUTPUT"
          elif echo "$msg" | grep -iq "#live"; then echo "channel=live" >> "$GITHUB_OUTPUT"
          else echo "channel=beta" >> "$GITHUB_OUTPUT"; fi
        shell: bash

      - name: Make build.sh executable
        run: chmod +x ./build.sh

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Run Nuke
        run: ./build.sh
        env:
          S3Endpoint: ${{ secrets.S3_ENDPOINT }}
          S3Region: ${{ secrets.S3_REGION }}
          S3Bucket: ${{ secrets.S3_BUCKET }}
          S3AccessKey: ${{ secrets.S3_ACCESS_KEY }}
          S3SecretKey: ${{ secrets.S3_SECRET_KEY }}
          Channel: ${{ steps.channel.outputs.channel }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_URL: ${{ secrets.SENTRY_URL }}
